<?php
/**
 * Instore Pickup Admin
 *
 * @package      :  Paypal_Instorepickupadmin
 * @version      :  0.1.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  01/03/2013
 *
 */
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Sales_Items_Column_Name
 */
?>

<?php if ($_item = $this->getItem()): ?>
    <h5 class="title"><span style="color:red;"><?php echo $this->htmlEscape($this->getSku()); ?></span>&nbsp;&nbsp;<span id="order_item_<?php echo $_item->getId() ?>_title"><?php echo $this->htmlEscape($_item->getName()) ?></span></h5>

    <?php if ($this->getOrderOptions()): ?>
        <div class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <label><?php echo $_option['label'] ?></label>
            <label>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $this->getCustomizedOptionValue($_option); ?>
            <?php else: ?>
                <?php $_option = $this->getFormattedOption($_option['value']); ?>
                <?php echo $_option['value']; ?>
                <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                    <span id="<?php echo $_dots = 'dots' . uniqid()?>"> ...</span>
                    <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_option['remainder'] ?></span>
                <?php endif; ?>
            <?php endif; ?>
            </label>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php echo strip_tags($_item->getDescription()) ?>
<?php endif; ?>
