<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<?php if(Mage::helper('paypal_instorepickupadmin')->useJqueryCDN()):?>
<link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/jquery.mobile/1.3.0/jquery.mobile-1.3.0.min.css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
<?php else : ?>
<link rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)?>paypal/instorepickup/jquery/jquery.mobile-1.3.0.min.css" />
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)?>paypal/instorepickup/jquery/jquery-1.8.2.min.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)?>paypal/instorepickup/jquery/jquery.mobile-1.3.0.min.js"></script>
<?php endif;?>
<?php echo $this->getCssJsHtml() ?>
