<?php
/**
 * Instore Pickup Admin
 *
 * @package      :  Paypal_Instorepickupadmin
 * @version      :  0.1.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  01/03/2013
 *
 */
?>
<img src="<?php echo $this->helper('paypal_instorepickupadmin')->getLogoUrl() ?>" alt="<?php echo $this->__('Magento Logo') ?>" class="logo"/>
<div data-role="header" data-theme="b" id="header-bar">
    <?php if($this->getIsShowHomeButton()):?>
    <a class="icon-home" href="<?php echo $this->getHomeUrl()?>" data-icon="home-big" data-iconpos="notext"><?php echo $this->__('Home')?></a>
    <?php else:?>
    <a style="display: none;" href="<?php echo $this->getHomeUrl()?>" data-icon="home" data-iconpos="notext"><?php echo $this->__('Home')?></a>
    <?php endif;?>
    <h1><?php echo $this->getTitle()?></h1>
    <a class="icon-logout" href="<?php echo $this->getLogoutUrl()?>" data-icon="logout" data-iconpos="notext" data-ajax="false"><?php echo $this->__('Logout')?></a>
</div>
