<?php
/**
 * Instore Pickup Admin
 *
 * @package      :  Paypal_Instorepickupadmin
 * @version      :  0.1.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  01/03/2013
 *
 */
?>
<?php $_order = $this->getOrder() ?>
<div style="clear: both;margin-top: 30px;"></div>
<table class="ui-responsive table-stroke bx-comment" >
    <thead>
    <tr>
        <th data-priority="1"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getFullHistory() as $_item): ?>
    <tr>
        <td>
            <?php if(!empty($_item['username'])):?>
            <strong>(<?php echo $_item['username']?>) </strong><br/>
            <?php endif;?>

            <?php if(!empty($_item['is_security'])):?>
            <strong style="color:red"><?php echo $this->__('SECURE') ?></strong><br/>
            <?php endif;?>
            <strong><?php echo $this->getItemCreatedAt($_item) ?></strong>
            <?php echo $this->getItemCreatedAt($_item, 'time') ?><span class="separator"> | </span>
            <strong><?php echo $this->getItemTitle($_item) ?></strong>
            <?php if ($this->isItemNotified($_item, false)): ?>
            <span class="separator"> | </span><small><?php echo $this->helper('sales')->__('Customer') ?>
                <strong class="subdue">
                    <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                    <?php echo $this->helper('sales')->__('Notification Not Applicable') ?>
                    <?php elseif ($this->isItemNotified($_item)): ?>
                    <?php echo $this->helper('sales')->__('Notified') ?>
                    <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="" />
                    <?php else: ?>
                    <?php echo $this->helper('sales')->__('Not Notified') ?>
                    <?php endif; ?>
                </strong></small>
            <?php endif; ?>
            <?php if ($_comment = $this->getItemComment($_item)): ?>
            <br/><?php echo $_comment ?>
            <?php endif; ?>
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>