<?php
/**
 * Instore Pickup Admin
 *
 * @package      :  Paypal_Instorepickupadmin
 * @version      :  0.1.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  01/03/2013
 *
 */
?>
<?php $_order = $this->getOrder() ?>
<?php $_items = $this->getItemsCollection() ?>

<ul data-role="listview" data-split-icon="gear" data-split-theme="d" data-inset="true">
    <?php $i=0;foreach ($_items as $_item):?>
        <?php if ($_item->getParentItem()) continue; else $i++;?>
            <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach;?>
</ul>
<?php if($_order->canShip()):?>
<a href="#" onclick="app.deliverAll()" style="float:right" data-role="button" data-mini="true" data-inline="true" data-icon="check" data-theme="b"><?php echo $this->__('Delivey All')?></a>
<?php endif;?>
<div style="clear: both;"></div>
