<?php
/**
 * PayPal Checkin
 *
 * @package      :  PayPal_Checkin
 * @version      :  0.9.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  19/03/2013
 * 
 */

if(Mage::helper('paypal_checkin')->getIsenabled() == true):
?>
<!-- Create PayPal Checkin Button -->
<button type="button" title="<?php echo $this->__('Checkin with PayPal') ?>" class="button btn-proceed-checkin btn-checkout" id="btn-checkin"><?php echo $this->__('Checkin with PayPal') ?></button>
<!-- Add script for click event -->
<script type="text/javascript">
    Event.observe('btn-checkin', 'click', function(){
        var $checkouturl = "<?php echo $this->getCheckoutURL() ?>";
        var $selectedDateTime;// = jQuery('#selectedDateTime');
        if($selectedDateTime != null){
            if($selectedDateTime.val() != ''){
                $checkouturl += "?selectedDateTime=" + $selectedDateTime.val();
                window.location = $checkouturl;
            }
        }
        else
            window.location = $checkouturl;
    }); 
</script>
<?php endif ?>