<?php
/**
 * Instore Pickup Admin
 *
 * @package      :  Paypal_Instorepickupadmin
 * @version      :  0.1.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  01/03/2013
 *
 */
?>
<!DOCTYPE html>
<html>
<head>
    <?php echo $this->getChildHtml('page_head') ?>
</head>
<body class="app">
<?php echo $this->getChildHtml('main')?>
</body>
<?php echo $this->getChildHtml('js')?>
</html>
