<?php
/**
 * PayPal Catalog
 *
 * @package      :  PayPal_Catalog
 * @version      :  0.9.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  19/03/2013
 * 
 */
?>
<?php $productListParams = $this->getRequest()->getParams(); ?>
<div class="content-box">
	<ul id="productList_<?php echo $productListParams['s'] ?>" class="product-list"><ul>
</div>
	
<script>
        selectNav(1);
        getProductListJSON("<?php echo $productListParams['id'] ?>","<?php echo $productListParams['s'] ?>");
</script>
