<?php
/**
 * PayPal Catalog
 *
 * @package      :  PayPal_Catalog
 * @version      :  0.9.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  19/03/2013
 * 
 */
?>
<?php $productViewParams = $this->getRequest()->getParams(); ?>
<form name="frm_<?php echo $productViewParams['s'] ?>" id="frm_<?php echo $productViewParams['s'] ?>" action="<?php echo Mage::app()->getStore()->getBaseUrl() ?>/jsoncheckout/cart/add" method="get">
    <div class="content-box">
        <input type="hidden" name="product" value="<?php echo $productViewParams['id'] ?>" />
        <div id="productError_<?php echo $productViewParams['s']; ?>" style="display:none"></div>
        <div id="productDetail_<?php echo $productViewParams['s'] ?>"></div>	
        <div id="productOption_<?php echo $productViewParams['s'] ?>"></div>
        <div id="productPrice_<?php echo $productViewParams['s'] ?>"></div>
            
        <div class="button-active" id="addtocart_<?php echo $productViewParams['s'] ?>" style="display:none">
            <a href="#"  onclick="addtocart(<?php echo $productViewParams['s'] ?>);" class="glossy-button"><?php echo $this->__('Add to Cart') ?></a>
        </div>
    </div>
</form>

<script>
    selectNav(1);
    getProductInfoJSON("<?php echo $productViewParams['id'] ?>","<?php echo $productViewParams['s'] ?>");
</script>