<?php
/**
 * Qrcodeorder
 *
 * @package      :  Paypal_Qrcodeorder
 * @version      :  0.9.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  19/03/2013
 * 
 */
?>
<?php if (Mage::getStoreConfig('checkout/qrcode/display_success_page')) : ?>
<img src="<?php echo $this->generateQrcode(); ?>" width="200px"/>
<div id="qrcode-description"><?php echo Mage::helper("paypal_qrcodeorder")->getStaticBlock(); ?></div>
<?php endif ?>