<?php
/**
 * PayPal Checkin
 *
 * @package      :  PayPal_Checkin
 * @version      :  0.9.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  19/03/2013
 * 
 */
?>
<?php if(Mage::helper('paypal_checkin')->getIsenabled() == true): ?>
<button type="button" title="<?php echo $this->__('Checkin with PayPal') ?>" class="button btn-proceed-checkin btn-checkin" id="btn-checkin"><?php echo $this->__('Checkin with PayPal') ?></button>
<script type="text/javascript">
    Event.observe('btn-checkin', 'click', function(){
        var $form = document.getElementById('product_addtocart_form');
        $form.action = '<?php echo $this->getAddToCartUrl() ?>';
        $form.submit();
    }); 
</script>
<?php endif ?>