<?php
/**
 * PayPal Checkout
 *
 * @package      :  PayPal_Checkout
 * @version      :  0.9.0
 * @since        :  Magento 1.7
 * @author       :  Paypal - http://www.paypal.com
 * @copyright    :  Copyright (C) 2013 Powered by Paypal
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  19/03/2013
 * 
 */
?>
<?php $confirmationParams = $this->getRequest()->getParams(); ?>
<div class="content-box greybg">
    
    <div id="merchant-box_<?php echo $confirmationParams['s']; ?>"></div>
        
    <div id="confirm-qr-box_<?php echo $confirmationParams['s']; ?>"></div>
        
    <div id="cart-list-box_<?php echo $confirmationParams['s']; ?>"></div>
        
    <div id="cart-total-box_<?php echo $confirmationParams['s']; ?>"></div>			
        
</div>

<script>
    selectNav(3);
    updateCartCount(<?php echo Mage::helper('paypal_checkout')->getNumberOfItems(); ?>);
    getConfirmPageJSON(<?php echo $confirmationParams['s']; ?>);
</script>